
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/*-----------------------------------
 Imports
 ------------------------------------*/
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import java.util.Set;
import java.util.TreeMap;
/**
 *
 * @author Hong
 */
public class Slicken1 extends javax.swing.JFrame {

    /**
     * Creates new form Slicken1
     */
    //Global variables necessary for running
    //a1 shows whether table exists
    public static boolean a1 = false;
    //The Jtable to display the results
    public static Jtable2 t1;
    //Whether one should keep the value displayed
    public static boolean keep = false;
    //Value varuables
    public static double phi;
    public static double alpha;
    public static double rho;
    public static String vectorvg;
    public static String vectorN;
    public static String phiio;
    public static String deltaio;
    public static String gammapo;
    public static String phipo;
    public static String deltao;
    public static String regimed;
    public static String sense;
    public static double[] phii = new double[4];
    public static double[] deltai = new double[4];
    public Slicken1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        regimes = new javax.swing.ButtonGroup();
        dial = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jButton3 = new javax.swing.JButton();
        dial1 = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jButton6 = new javax.swing.JButton();
        dial2 = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane3 = new javax.swing.JTextPane();
        jButton8 = new javax.swing.JButton();
        phiS = new javax.swing.JDialog();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextPane5 = new javax.swing.JTextPane();
        jButton10 = new javax.swing.JButton();
        phiS1 = new javax.swing.JDialog();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextPane6 = new javax.swing.JTextPane();
        jButton11 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        phpi3 = new javax.swing.JTextField();
        ri2 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        phpi4 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        ai2 = new javax.swing.JTextField();
        dpi3 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        dpi2 = new javax.swing.JTextField();
        phpi2 = new javax.swing.JTextField();
        phi2 = new javax.swing.JTextField();
        dpi4 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        gpo2 = new java.awt.TextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        dgo2 = new java.awt.TextField();
        jLabel21 = new javax.swing.JLabel();
        no2 = new java.awt.TextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        vgo2 = new java.awt.TextField();
        phpo2 = new java.awt.TextField();
        jLabel25 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        panel1 = new java.awt.Panel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane4 = new javax.swing.JTextPane();

        dial.setTitle("Reminder");
        dial.setAlwaysOnTop(true);
        dial.setMinimumSize(new java.awt.Dimension(370, 180));

        jPanel1.setAlignmentX(200.0F);
        jPanel1.setAlignmentY(200.0F);

        jButton2.setText("Keep");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextPane1.setBackground(new java.awt.Color(240, 240, 240));
        jTextPane1.setBorder(null);
        jTextPane1.setText("Due to original measurement errors, the input data may not be accurate enough. You can choose whether you want to use this data.");
        jScrollPane1.setViewportView(jTextPane1);

        jButton3.setText("Discard");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(32, 32, 32)
                .addComponent(jButton3)
                .addGap(115, 115, 115))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        javax.swing.GroupLayout dialLayout = new javax.swing.GroupLayout(dial.getContentPane());
        dial.getContentPane().setLayout(dialLayout);
        dialLayout.setHorizontalGroup(
            dialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        dialLayout.setVerticalGroup(
            dialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        dial1.setTitle("Reminder");
        dial1.setAlwaysOnTop(true);
        dial1.setMinimumSize(new java.awt.Dimension(370, 180));

        jPanel3.setAlignmentX(200.0F);
        jPanel3.setAlignmentY(200.0F);

        jButton4.setText("Keep");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTextPane2.setBackground(new java.awt.Color(240, 240, 240));
        jTextPane2.setBorder(null);
        jTextPane2.setText("The dip direction of the plane is nearly parallel to the trend of sigma 3. You can choose whether you want to use this data.");
        jScrollPane2.setViewportView(jTextPane2);

        jButton6.setText("Discard");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jButton4)
                        .addGap(31, 31, 31)
                        .addComponent(jButton6)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton6)))
        );

        javax.swing.GroupLayout dial1Layout = new javax.swing.GroupLayout(dial1.getContentPane());
        dial1.getContentPane().setLayout(dial1Layout);
        dial1Layout.setHorizontalGroup(
            dial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dial1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        dial1Layout.setVerticalGroup(
            dial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dial1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        dial2.setTitle("Reminder");
        dial2.setAlwaysOnTop(true);
        dial2.setMinimumSize(new java.awt.Dimension(370, 180));

        jPanel6.setAlignmentX(200.0F);
        jPanel6.setAlignmentY(200.0F);

        jButton7.setText("Keep");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jTextPane3.setBackground(new java.awt.Color(240, 240, 240));
        jTextPane3.setBorder(null);
        jTextPane3.setText("The dip direction of the plane is nearly parallel to the trend of sigma 2. You can choose whether you want to use this data.");
        jScrollPane3.setViewportView(jTextPane3);

        jButton8.setText("Discard");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jButton7)
                        .addGap(40, 40, 40)
                        .addComponent(jButton8)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton8))
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout dial2Layout = new javax.swing.GroupLayout(dial2.getContentPane());
        dial2.getContentPane().setLayout(dial2Layout);
        dial2Layout.setHorizontalGroup(
            dial2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dial2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        dial2Layout.setVerticalGroup(
            dial2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        phiS.setTitle("Warning");
        phiS.setAlwaysOnTop(true);
        phiS.setMinimumSize(new java.awt.Dimension(370, 180));

        jPanel7.setAlignmentX(200.0F);
        jPanel7.setAlignmentY(200.0F);

        jTextPane5.setBackground(new java.awt.Color(240, 240, 240));
        jTextPane5.setBorder(null);
        jTextPane5.setText("The principal stresses are not correct. The result will be automatically discarded.");
        jScrollPane5.setViewportView(jTextPane5);

        jButton10.setText("Discard");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jButton10)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton10)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout phiSLayout = new javax.swing.GroupLayout(phiS.getContentPane());
        phiS.getContentPane().setLayout(phiSLayout);
        phiSLayout.setHorizontalGroup(
            phiSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(phiSLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        phiSLayout.setVerticalGroup(
            phiSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(phiSLayout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                .addContainerGap())
        );

        phiS1.setTitle("Warning");
        phiS1.setAlwaysOnTop(true);
        phiS1.setMinimumSize(new java.awt.Dimension(370, 180));

        jPanel8.setAlignmentX(200.0F);
        jPanel8.setAlignmentY(200.0F);

        jTextPane6.setBackground(new java.awt.Color(240, 240, 240));
        jTextPane6.setBorder(null);
        jTextPane6.setText("The dip of the plane is nearly equal to the plunge of the steepest principal stress. The result will be automatically discarded.");
        jScrollPane6.setViewportView(jTextPane6);

        jButton11.setText("Discard");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jButton11)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton11)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout phiS1Layout = new javax.swing.GroupLayout(phiS1.getContentPane());
        phiS1.getContentPane().setLayout(phiS1Layout);
        phiS1Layout.setHorizontalGroup(
            phiS1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(phiS1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        phiS1Layout.setVerticalGroup(
            phiS1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Slicken 1.0");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setText("Slicken 1.0");

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton1.setText("Calculate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        phpi3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                phpi3FocusGained(evt);
            }
        });
        phpi3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phpi3ActionPerformed(evt);
            }
        });

        ri2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ri2FocusGained(evt);
            }
        });
        ri2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ri2ActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Dip angle of plane");

        phpi4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                phpi4FocusGained(evt);
            }
        });
        phpi4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phpi4ActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Stress Ratio");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel14.setText("Input: Slip vector under a stress field");

        ai2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ai2FocusGained(evt);
            }
        });

        dpi3.setToolTipText("");
        dpi3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dpi3FocusGained(evt);
            }
        });
        dpi3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dpi3ActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Dip direction of plane");

        dpi2.setToolTipText("");
        dpi2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dpi2FocusGained(evt);
            }
        });
        dpi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dpi2ActionPerformed(evt);
            }
        });

        phpi2.setMinimumSize(new java.awt.Dimension(6, 89));
        phpi2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                phpi2FocusGained(evt);
            }
        });
        phpi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phpi2ActionPerformed(evt);
            }
        });

        phi2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                phi2FocusGained(evt);
            }
        });

        dpi4.setToolTipText("");
        dpi4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dpi4FocusGained(evt);
            }
        });
        dpi4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dpi4ActionPerformed(evt);
            }
        });

        jButton5.setText("Open table window");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setText("<html>Plunge of &sigma;3 </html>");

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel27.setText("<html>Plunge of &sigma;2 </html>");

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel28.setText("<html>Plunge of &sigma;1 </html>");

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel29.setText("<html>Trend of &sigma;2 </html>");

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel30.setText("<html>Trend of &sigma;1 </html>");

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel31.setText("<html>Trend of &sigma;3 </html>");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(phi2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ai2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(phpi2, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(dpi2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(phpi3, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(dpi3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(phpi4, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(dpi4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(jButton1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel14)
                        .addGap(4, 4, 4)
                        .addComponent(jButton5))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ri2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jButton5))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17)
                                    .addComponent(ai2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(phi2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(ri2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(phpi2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(phpi3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phpi4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dpi4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(dpi3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(dpi2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addComponent(jButton1)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        gpo2.setEditable(false);

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setText("Vector of slip");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("Plunge of slip");

        dgo2.setEditable(false);
        dgo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dgo2ActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText("Rake of slip");

        no2.setEditable(false);
        no2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no2ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel15.setText("Output");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setText("Vector normal to the plane");

        vgo2.setEditable(false);
        vgo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vgo2ActionPerformed(evt);
            }
        });

        phpo2.setEditable(false);

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setText("Trend of slip");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addComponent(jLabel15)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dgo2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addGap(27, 27, 27)))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(no2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(vgo2, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE))))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel21)
                .addGap(5, 5, 5)
                .addComponent(gpo2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(phpo2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(gpo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel25))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dgo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel22)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(phpo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(no2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel23)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(vgo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 576, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Slicken", jPanel2);

        panel1.setBackground(new java.awt.Color(240, 240, 240));

        jTextPane4.setEditable(false);
        jTextPane4.setBackground(new java.awt.Color(240, 240, 240));
        jTextPane4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextPane4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextPane4.setText("Instructions\n\nSlickenLines Window\n\tThe SlickenLines window, in which you are currently in, presents the user with three cases to perform slicken lines calculation. In all three cases, in order to use the algorithms, insert all the input values and press the bottom to perform the calculations. When this is done, the calculated output will be shown in the output section of the case and also in a separate window with an output table will appear.\n\t\n\nOutput table Window\n\tThe output table windows for each case allows you to see the output of current and previous calculations. It also allows to save and load files for ease of use and retrieval. The files are saved in UNICODE UTF-8 format with .slc1, .slc2, or .slc3 file extensions, for each case respectively. \n\nFor detailed instructions, please reference the user guide.");
        jScrollPane4.setViewportView(jTextPane4);

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Instructions and Help", jPanel10);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 574, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(244, 244, 244)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /*----------------------------------------------
     Buttons and text areas
     -----------------------------------------------*/
    /*-----------------------------------
     Function group jButtonXActionPerformed
     Displays table in case the user wants to keep the results when an error message is shown, other wise dispose.
     ------------------------------------*/
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        keep = true;
        t1.addNewEntry(String.format("%.4g", Math.toDegrees(phi)), String.format("%.4g", Math.toDegrees(alpha)), String.format("%.4g",rho),regimed, String.format("%.4g", Math.toDegrees(phii[1])), String.format("%.4g", Math.toDegrees(phii[2])), String.format("%.4g", Math.toDegrees(phii[3])), String.format("%.4g", Math.toDegrees(deltai[1])), String.format("%.4g", Math.toDegrees(deltai[2])), String.format("%.4g", Math.toDegrees(deltai[3])),  gammapo, sense, phipo, deltao, vectorN, vectorvg);        dial.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        keep = false;
        dial.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        keep = true;
        t1.addNewEntry(String.format("%.4g", Math.toDegrees(phi)), String.format("%.4g", Math.toDegrees(alpha)), String.format("%.4g",rho),regimed, String.format("%.4g", Math.toDegrees(phii[1])), String.format("%.4g", Math.toDegrees(phii[2])), String.format("%.4g", Math.toDegrees(phii[3])), String.format("%.4g", Math.toDegrees(deltai[1])), String.format("%.4g", Math.toDegrees(deltai[2])), String.format("%.4g", Math.toDegrees(deltai[3])),  gammapo, sense, phipo, deltao, vectorN, vectorvg);        dial1.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        keep = false;
        dial1.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        keep = true;
        t1.addNewEntry(String.format("%.4g", Math.toDegrees(phi)), String.format("%.4g", Math.toDegrees(alpha)), String.format("%.4g",rho),regimed, String.format("%.4g", Math.toDegrees(phii[1])), String.format("%.4g", Math.toDegrees(phii[2])), String.format("%.4g", Math.toDegrees(phii[3])), String.format("%.4g", Math.toDegrees(deltai[1])), String.format("%.4g", Math.toDegrees(deltai[2])), String.format("%.4g", Math.toDegrees(deltai[3])),  gammapo, sense, phipo, deltao, vectorN, vectorvg);        dial2.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        keep = false;
        dial2.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        phiS.dispose();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        phiS1.dispose();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void vgo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vgo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vgo2ActionPerformed

    private void no2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_no2ActionPerformed

    private void dgo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dgo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dgo2ActionPerformed
    /*----------------------------------------------
     Function jButton5ActionPerformed
     This opens a table if a table a table is not visible yet
     -----------------------------------------------*/
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        if(t1 == null){
            t1 = new Jtable2();
            t1.setVisible(true);
            a1 = true;
        }
        else if(!t1.isVisible()){
            t1.setVisible(true);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void dpi4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dpi4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dpi4ActionPerformed

    private void dpi4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dpi4FocusGained
        if(dpi4.getText().equals("Delta sub 3 value"))dpi4.setText("");
    }//GEN-LAST:event_dpi4FocusGained

    private void phi2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phi2FocusGained
        if(phi2.getText().equals("Phi value"))phi2.setText("");
    }//GEN-LAST:event_phi2FocusGained

    private void phpi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phpi2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phpi2ActionPerformed

    private void phpi2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phpi2FocusGained
        if(phpi2.getText().equals("Phi sub 1 value"))phpi2.setText("");
    }//GEN-LAST:event_phpi2FocusGained

    private void dpi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dpi2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dpi2ActionPerformed

    private void dpi2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dpi2FocusGained
        if(dpi2.getText().equals("Delta sub 1 value"))dpi2.setText("");
    }//GEN-LAST:event_dpi2FocusGained

    private void dpi3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dpi3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dpi3ActionPerformed

    private void dpi3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dpi3FocusGained
        if(dpi3.getText().equals("Delta sub 2 value"))dpi3.setText("");
    }//GEN-LAST:event_dpi3FocusGained

    private void ai2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ai2FocusGained
        if(ai2.getText().equals("Alpha value"))ai2.setText("");
    }//GEN-LAST:event_ai2FocusGained

    private void phpi4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phpi4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phpi4ActionPerformed

    private void phpi4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phpi4FocusGained
        if(phpi4.getText().equals("Phi sub 3 value"))phpi4.setText("");
    }//GEN-LAST:event_phpi4FocusGained

    private void ri2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ri2FocusGained
        if(ri2.getText().equals("Rho value"))ri2.setText("");
    }//GEN-LAST:event_ri2FocusGained

    private void ri2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ri2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ri2ActionPerformed

    private void phpi3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phpi3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phpi3ActionPerformed

    private void phpi3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phpi3FocusGained
        if(phpi3.getText().equals("Phi sub 2 value"))phpi3.setText("");
    }//GEN-LAST:event_phpi3FocusGained

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Input
        keep = true;
        phi = Math.toRadians(Double.parseDouble(phi2.getText()));
        alpha = Math.toRadians(Double.parseDouble(ai2.getText()));
        rho = Double.parseDouble(ri2.getText());

       
        phii[1] = Math.toRadians(Double.parseDouble(phpi2.getText()));
        phii[2] = Math.toRadians(Double.parseDouble(phpi3.getText()));
        phii[3] = Math.toRadians(Double.parseDouble(phpi4.getText()));

        
        deltai[1] = Math.toRadians(Double.parseDouble(dpi2.getText()));
        deltai[2] = Math.toRadians(Double.parseDouble(dpi3.getText()));
        deltai[3] = Math.toRadians(Double.parseDouble(dpi4.getText()));

        /*----------------------------------------------
        Calculations
         -----------------------------------------------*/
        //lmn matrix
        //Equations 6a,6b,6c
        double[] li = new double[4];
        double[] mi = new double[4];
        double[] ni = new double[4];
        for(int i = 1; i < 4; i++){
            li[i] = Math.cos(deltai[i])*Math.cos(phii[i]);
            mi[i] = Math.cos(deltai[i])*Math.sin(phii[i]);
            ni[i] = Math.sin(deltai[i]);
        }
        
        //Equation 5
        double ln = -1*Math.cos(phi)*Math.sin(alpha);
        double mn = -1*Math.sin(alpha)*Math.sin(phi);
        double nn = Math.cos(alpha);
        
        //Equation 7
        double l11 = li[1]*ln + mi[1]*mn + ni[1]*nn;
        double l22 = li[2]*ln + mi[2]*mn + ni[2]*nn;
        double l33 = li[3]*ln + mi[3]*mn + ni[3]*nn;
        
        //Equation 8, 9, 10, 11
        regimed = "Extension";
        double r = 1/rho;
        double k = l22*l22+l11*l11*r;
        double vs3 = -k*l33;
        double vs2 = (1-k)*l22;
        double vs1 = (r-k)*l11;
       

        //Equation 12
        double vg1 = li[1]*vs1 + li[2]*vs2 + li[3]*vs3;
        double vg2 = mi[1]*vs1 + mi[2]*vs2 + mi[3]*vs3;
        double vg3 = ni[1]*vs1 + ni[2]*vs2 + ni[3]*vs3;
        
        //Equation 13
        double vgmag = Math.sqrt(vg1*vg1 + vg2*vg2 + vg3*vg3);
        double v1g = vg1/vgmag;
        double v2g = vg2/vgmag;
        double v3g = vg3/vgmag;
        

        //Equation 14
        double deltag = Math.asin(Math.abs(v3g));

       
        /*----------------------------------------------
        Phip and gammap
        -----------------------------------------------*/
        
        //Equation 15
        double gamma = Math.acos(Math.tan(deltag)/Math.tan(alpha));
        if(deltag < 0) gamma = Math.acos(Math.tan(-deltag)/Math.tan(alpha));
        if(alpha == 0) gamma = Math.PI;
        if(Math.tan(Math.abs(deltag)) > Math.tan(alpha)) gamma = 0;
        
        
        double phis = phi - Math.PI/2;
        
        
        double vss1 = Math.cos(phis);
        double vss2 = Math.sin(phis);
        double vss3 = 0;
        
        //Equation 17 & 18
        double theta = Math.acos((v1g*vss1 + v2g*vss2 + v3g*vss3));
        double costheta = Math.cos(theta);
        
        //Equation 19
        double phip = phi - gamma;
        
        //Equation 20 - 24
        double gammap = theta;
        if(v3g >= 0 && costheta > 0){
            phip = phi - gamma;
            gammap = theta;
            System.out.println("Case 1");
        }
        else if(v3g > 0 && costheta <= 0){
            phip = phi + gamma;
            gammap = theta;
            System.out.println("Case 2");
        }
        else if(v3g <= 0 && costheta > 0){
            phip = phi + gamma;
            gammap = 2*Math.PI - theta;
            System.out.println("Case 3");
        }
        else if(v3g < 0 && costheta <= 0){
            phip = phi - gamma;
            gammap = 2*Math.PI - theta;
            System.out.println("Case 4");
        }
        while(gammap > 2*Math.PI) gammap -= 2*Math.PI;
        while(gammap < 0) gammap += 2*Math.PI;
        while(phip < 0) phip += 2*Math.PI;
        while(phip > 2*Math.PI) phip -= 2*Math.PI;
        /*----------------------------------------------
        Output prep
        -----------------------------------------------*/
        if(v1g < 0.0001 && v1g > -0.0001) v1g = 0;
        if(v2g < 0.0001 && v2g > -0.0001) v2g = 0;
        if(v3g < 0.0001 && v3g > -0.0001) v3g = 0;
        if(ln < 0.0001 && ln > -0.0001) ln = 0;
        if(mn < 0.0001 && mn > -0.0001) mn = 0;
        if(nn < 0.0001 && nn > -0.0001) nn = 0;
        /*----------------------------------------------
        Output
        -----------------------------------------------*/
        vectorvg = "(" + String.format("%.4g",v1g) + ", " + String.format("%.4g",v2g) + ", "+ String.format("%.4g",v3g) + ")" ;
        vgo2.setText(vectorvg);

        vectorN = "(" + String.format("%.4g",ln) + ", " + String.format("%.4g",mn) + ", "+ String.format("%.4g",nn) + ")" ;
        phiio = "(" + String.format("%.4g",Math.toDegrees(phii[1])) + ", " + String.format("%.4g",Math.toDegrees(phii[2])) + ", "+ String.format("%.4g",Math.toDegrees(phii[3])) + ")" ;
        deltaio = "(" + String.format("%.4g",Math.toDegrees(deltai[1])) + ", " + String.format("%.4g",Math.toDegrees(deltai[2])) + ", "+ String.format("%.4g",Math.toDegrees(deltai[3])) + ")" ;
        no2.setText(vectorN);

        gammapo = String.format("%.4g",Math.toDegrees(gammap));
        gpo2.setText(gammapo);

        phipo = String.format("%.4g",Math.toDegrees(phip));
        phpo2.setText(phipo);

        deltao = String.format("%.4g",Math.toDegrees(deltag));
        dgo2.setText(deltao);
        /*----------------------------------------------
        Table
        -----------------------------------------------*/
        if(t1 == null){
            t1 = new Jtable2();
            t1.setVisible(true);
            a1 = true;
        }
        else if(!t1.isVisible()){
            t1.setVisible(true);
        }
        /*----------------------------------------------
        Epsilon test
        -----------------------------------------------*/
        double epsilon = Math.atan(Math.tan(Math.toRadians(3))/Math.tan(alpha));
        double tha = Math.PI - Math.acos((li[3] * ln + mi[3] * mn + ni[3] * nn));
        double thb = Math.acos((li[2] * ln + mi[2] * mn + ni[2] * nn));
        
        //Calculate sense
        sense = "1";
        if(gammap < Math.PI/2 && gammap > 0) sense = "1";
        if(gammap < Math.PI && gammap > Math.PI/2) sense = "2";
        if(gammap < 3*Math.PI/2 && gammap > Math.PI) sense = "3";
        if(gammap < 2*Math.PI && gammap > 3*Math.PI/2) sense = "4";
        if(Math.abs(gammap) <= Math.toRadians(5)||(gammap <= Math.toRadians(360) && gammap >= Math.toRadians(355))) sense = "5";
        if(Math.abs(Math.abs(gammap) - Math.PI) <= Math.toRadians(5)) sense = "6";
        if(Math.abs(Math.abs(gammap) - Math.PI/2) <= Math.toRadians(5)) sense = "7";
        if(Math.abs(Math.abs(gammap) - 3*Math.PI/2) <= Math.toRadians(5)) sense = "8";
        
        //Test error message conditions
        if(epsilon > Math.toRadians(8)) {
            dial.setVisible(true);
        }
        else if(epsilon > Math.toRadians(10)) {
            dial.setVisible(true);
        }
        else if(epsilon > Math.toRadians(10)) {
            dial.setVisible(true);
        }
        else{
            if((tha < Math.toRadians(5) && tha > Math.toRadians(-5))) {
                dial1.setVisible(true);
            }
            else if((thb < Math.toRadians(5) && thb > Math.toRadians(-5))) {
                dial2.setVisible(true);
            }
            else if((tha < Math.toRadians(5) && tha > Math.toRadians(-5))) {
                dial1.setVisible(true);
            }
            else{t1.addNewEntry(String.format("%.4g", Math.toDegrees(phi)), String.format("%.4g", Math.toDegrees(alpha)), String.format("%.4g",rho),regimed, String.format("%.4g", Math.toDegrees(phii[1])), String.format("%.4g", Math.toDegrees(phii[2])), String.format("%.4g", Math.toDegrees(phii[3])), String.format("%.4g", Math.toDegrees(deltai[1])), String.format("%.4g", Math.toDegrees(deltai[2])), String.format("%.4g", Math.toDegrees(deltai[3])),  gammapo, sense, phipo, deltao, vectorN, vectorvg);}
        }
                
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Slicken1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Slicken1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Slicken1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Slicken1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Slicken1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ai2;
    private java.awt.TextField dgo2;
    private javax.swing.JDialog dial;
    private javax.swing.JDialog dial1;
    private javax.swing.JDialog dial2;
    private javax.swing.JTextField dpi2;
    private javax.swing.JTextField dpi3;
    private javax.swing.JTextField dpi4;
    private java.awt.TextField gpo2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JTextPane jTextPane3;
    private javax.swing.JTextPane jTextPane4;
    private javax.swing.JTextPane jTextPane5;
    private javax.swing.JTextPane jTextPane6;
    private java.awt.TextField no2;
    private java.awt.Panel panel1;
    private javax.swing.JTextField phi2;
    private javax.swing.JDialog phiS;
    private javax.swing.JDialog phiS1;
    private javax.swing.JTextField phpi2;
    private javax.swing.JTextField phpi3;
    private javax.swing.JTextField phpi4;
    private java.awt.TextField phpo2;
    private javax.swing.ButtonGroup regimes;
    private javax.swing.JTextField ri2;
    private java.awt.TextField vgo2;
    // End of variables declaration//GEN-END:variables
}
